### ISSUE TITLE
bash: line 76: jq: command not found when running `expose-keptn.sh`, `configure-istio.sh` and `multistage-delivery.sh`

### ISSUE THREAD

**Issue by TannerGilbert** [keptn/examples#223]
Sinece #222 the [istio-configuration/configure-istio.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/istio-configuration/configure-istio.sh), [quickstart/expose-keptn.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/quickstart/expose-keptn.sh) and [quickstart/multistage-delivery.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/quickstart/multistage-delivery.sh) use [jq](https://stedolan.github.io/jq/) to parse JSON output of the `kubectl version -ojson` command.

This works well if the person executing the file already has [jq](https://stedolan.github.io/jq/) installed but fails with the following error otherwise:

``` 
bash: line 76: jq: command not found
```

To make the script run the use has to [install jq](https://stedolan.github.io/jq/download/) but there might be better solutions to solve this so the user doesn't need to take any extra steps. For example we could replace:

```
K8S_VERSION_MINOR=$(echo "$K8S_VERSION" | jq -r .serverVersion.minor)
```

with:

```
K8S_VERSION_MINOR=$(echo "$K8S_VERSION" | python -c "import sys, json; print(json.load(sys.stdin)['serverVersion']['minor'])")
```

which would now only require python to run (preinstalled on most systems).

**Comment by mowies** [comment]
If we already switch out the third-party dependency (`jq`) then I would go the extra mile and remove it instead of introducing another third-party dependency. Yes, python is more standard than `jq`, but still not always pre-installed and definitely not always just with the `python` command. (think about e.g. `python3`, `python36`, `python` pointing to Python 2.7, etc.)

I think this can also be solved with a fancy grep or so :)
